apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydeploy1
  template:
    metadata:
      labels:
        app: mydeploy1
    spec:
      containers:
        - name: mycontainer
          image: logeshwaran2025/ci-cd-pipelines:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
