apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  selector:
    app: mydeploy1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32233
